import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Providers } from './providers'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 
    <html lang="en" suppressHydrationWarning>
      {/* Apply Montserrat to the entire body, but keep Inter available if needed */}
      <body className={montserrat.className}>
      <Providers>
            {children}
        </Providers>
        
        </body>
    </html>
  );
}
